### ISSUE TITLE
Hypovereinsbank requires mobileTAN 904 Two-Factor Method

### ISSUE THREAD

**Issue by sims1253** [bnw/firefly-iii-fints-importer#104]
See title. When I try 901 or 942, I get the following error and 904 is not available as an option:
```
Fatal error: Uncaught AssertionError: Your bank did not accept your tan mode 942. Accepted modes are: 904 in /app/FinTsFactory.php:58 Stack trace: #0 /app/FinTsFactory.php(58): assert(false, 'Your bank did n...') #1 /app/FinTsFactory.php(30): App\FinTsFactory::get_tan_mode(Object(Fhp\FinTs), Object(Symfony\Component\HttpFoundation\Session\Session)) #2 /app/Choose2FADevice.php(25): App\FinTsFactory::create_from_session(Object(Symfony\Component\HttpFoundation\Session\Session)) #3 /app/index.php(55): App\StepFunction\Choose2FADevice() #4 {main} thrown in /app/FinTsFactory.php on line 58
```

I guess technically 904 is appTAN?

**Comment by bnw** [comment]
Hi, 
I added mode 904. Please give it a try and reopen, if there are any problems :)

**Comment by sims1253** [comment]
Thanks for the quick answer. It worked in so far that I could request a TAN and enter it (and my phone gave me one, so that seems to work) but then I got an error which I'm not sure about what it means:

```
Fatal error: Uncaught GrumpyDictator\FFIIIApiSupport\Exceptions\ApiHttpException: Error accessing "http://xxx.xxx.xxx.xx:xxxx//api/v1/accounts?type=asset&page=1&limit=250". Status code is 404. Body is: {"message":"Resource not found","exception":"NotFoundHttpException"} in /vendor/firefly-iii/api-support-classes/src/Request/Request.php:206 Stack trace: #0 /vendor/firefly-iii/api-support-classes/src/Request/GetAccountsRequest.php(80): GrumpyDictator\FFIIIApiSupport\Request\Request->authenticatedGet() #1 /app/ChooseAccount.php(38): GrumpyDictator\FFIIIApiSupport\Request\GetAccountsRequest->get() #2 /app/index.php(63): App\StepFunction\ChooseAccount() #3 {main} thrown in /vendor/firefly-iii/api-support-classes/src/Request/Request.php on line 206
```

**Comment by bnw** [comment]
Hm, notice the double `//` in the address (after the `:xxxx`). Can you try to remove the trailing `/` in your configured Firefly URL?

**Comment by sims1253** [comment]
m( works splendidly :) 
Can I buy you a coffee/beer for the support?
Now I just have to play around with the regex for it to put everything into the right fields, as some things seem off. 
Thanks again!
