### ISSUE TITLE
Import no longer working 

### ISSUE THREAD

**Issue by psistorm** [bnw/firefly-iii-fints-importer#121]
Hi there,

I was using the importer once every month in the past few months and now there is suddenly the following error:

```
FinTS errors: 9050 (global): Die Nachricht enthält Fehler. 9800 (global): Dialog abgebrochen 9120 (global): Die Nachricht hat nicht die erwartete Nachrichtennummer. 9010 (wrt seg 3): Auftrag wegen genereller Fehler in Auftragsnachricht nicht verarbeitet. Request segments: HKSPA:3:2
```
I haven't changed anything besides updating Firefly and the importer some days ago.

Thanks in advance!

**Comment by psistorm** [comment]
The complete error message is 
```

Fatal error: Uncaught Fhp\Protocol\ServerException: FinTS errors: 9050 (global): Die Nachricht enthält Fehler. 9800 (global): Dialog abgebrochen 9120 (global): Die Nachricht hat nicht die erwartete Nachrichtennummer. 9010 (wrt seg 3): Auftrag wegen genereller Fehler in Auftragsnachricht nicht verarbeitet. Request segments: HKSPA:3:2' in /vendor/nemiah/php-fints/lib/Fhp/Protocol/ServerException.php:170 Stack trace: #0 /vendor/nemiah/php-fints/lib/Fhp/FinTs.php(963): Fhp\Protocol\ServerException::detectAndThrowErrors(Object(Fhp\Protocol\Message), Object(Fhp\Protocol\Message)) #1 /vendor/nemiah/php-fints/lib/Fhp/FinTs.php(307): Fhp\FinTs->sendMessage(Object(Fhp\Protocol\Message)) #2 /app/ChooseAccount.php(22): Fhp\FinTs->execute(Object(Fhp\Action\GetSEPAAccounts)) #3 /app/TanHandler.php(41): App\StepFunction\{closure}() #4 /app/TanHandler.php(31): App\TanHandler->create_or_continue_action() #5 /app/ChooseAccount.php(19): App\TanHandler->__construct(Object(Closure), 'list-accounts', Object(Symfony\Component\HttpFoundation\Session\Session), Object(Twig\Environment), Object(Fhp\FinTs), Object(App\Step), Object(Symfony\Component\HttpFoundation\Request)) #6 /app/index.php(63): App\StepFunction\ChooseAccount() #7 {main} thrown in /vendor/nemiah/php-fints/lib/Fhp/Protocol/ServerException.php on line 170

```
