### ISSUE TITLE
Wrong config.json?

### ISSUE THREAD

**Issue by Se7enair** [bnw/firefly-iii-fints-importer#126]
I tried to using a config.json, but get this error.

`Fatal error: Uncaught GrumpyDictator\FFIIIApiSupport\Exceptions\ApiHttpException: cURL error 35: error:1408F10B:SSL routines:ssl3_get_record:wrong version number (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://192.168.178.112:4000/api/v1/accounts?type=asset&page=1&limit=250 in /vendor/firefly-iii/api-support-classes/src/Request/Request.php:347 Stack trace: #0 /vendor/firefly-iii/api-support-classes/src/Request/Request.php(194): GrumpyDictator\FFIIIApiSupport\Request\Request->handleException(Object(GuzzleHttp\Exception\ConnectException)) #1 /vendor/firefly-iii/api-support-classes/src/Request/GetAccountsRequest.php(80): GrumpyDictator\FFIIIApiSupport\Request\Request->authenticatedGet() #2 /app/ChooseAccount.php(38): GrumpyDictator\FFIIIApiSupport\Request\GetAccountsRequest->get() #3 /app/index.php(63): App\StepFunction\ChooseAccount() #4 {main} thrown in /vendor/firefly-iii/api-support-classes/src/Request/Request.php on line 347`

This is my config. Am I right that bank_account_iban is the one which is saved inside firefly? And how can I choose the account to import from? My bank, ING, provides 4 accounts behind my login.

```
{
    "bank_username": "redacted",
    "bank_password": "redacted",
    "bank_code": "redacted",
    "bank_url": "redacted",
    "bank_2fa": "NoPsd2TanMode",
    "bank_2fa_device": "",
    "firefly_url": "hredacted",
    "firefly_access_token": "redacted",
    "skip_transaction_review": "false",
    "__description_regex_comment__": "To disable the regex search & replace of the transaction description, set both to an empty string.",
    "description_regex_match": "",
    "description_regex_replace": "",
    "auto_submit_form_via_js": false,
    "choose_account_automation":
    {
      "bank_account_iban": "redacted",
      "firefly_account_id": "redacted",
      "__from_to_comment__": "The following values will be passed directly into DateTime. Set them to null to choose them manually during import process.",
      "from": "now - 7 days",
      "to": "now"
    }
  }
   
```

**Comment by Se7enair** [comment]
Had https instead of http in the url.
