### ISSUE TITLE
Fatal Error when adding ING

### ISSUE THREAD

**Issue by crashmit** [bnw/firefly-iii-fints-importer#133]
Hey there, 

I've successfully added an account with DKB, but struggle to do the same for my ING account. When trying to do it, I get the following error for the following configuration.
I've made sure, that I don't have any trailing slashes and double-checked that my PIN is correct.

<img width="586" alt="image" src="https://github.com/bnw/firefly-iii-fints-importer/assets/58466626/c3eb36b0-4461-4627-8621-2f01447205f8">

`Fatal error: Uncaught Fhp\Protocol\ServerException: FinTS errors: 9800 (global): Der Dialog wurde abgebrochen. 9010 (global): Unerwartete Nachrichtennummer. Bitte melden Sie sich erneut an. in /vendor/nemiah/php-fints/lib/Fhp/Protocol/ServerException.php:170 Stack trace: #0 /vendor/nemiah/php-fints/lib/Fhp/FinTs.php(963): Fhp\Protocol\ServerException::detectAndThrowErrors(Object(Fhp\Protocol\Message), Object(Fhp\Protocol\Message)) #1 /vendor/nemiah/php-fints/lib/Fhp/FinTs.php(307): Fhp\FinTs->sendMessage(Object(Fhp\Protocol\Message)) #2 /vendor/nemiah/php-fints/lib/Fhp/FinTs.php(263): Fhp\FinTs->execute(Object(Fhp\Protocol\DialogInitialization)) #3 /app/Login.php(23): Fhp\FinTs->login() #4 /app/TanHandler.php(41): App\StepFunction\{closure}() #5 /app/TanHandler.php(31): App\TanHandler->create_or_continue_action() #6 /app/Login.php(21): App\TanHandler->__construct(Object(Closure), 'login-action', Object(Symfony\Component\HttpFoundation\Session\Session), Object(Twig\Environment), Object(Fhp\FinTs), Object(App\Step), Object(Symfony\Component\HttpFoundation\Request)) #7 /app/index.php(59): App\StepFunction\Login() #8 {main} thrown in /vendor/nemiah/php-fints/lib/Fhp/Protocol/ServerException.php on line 170`

**Comment by se7entynine** [comment]
May I ask how did added the DKB account? Sorry for no help on your current issue.

**Comment by crashmit** [comment]
Sure, I also used the GUI solution and actually went with the hint texts as they're referring to the DKB. This means the sample URL, sample BLZ and as 2FA I used 921. Username and password similar to what you log in with on the web portal. Or do you struggle to get to the page displayed in the screenshot?

**Comment by se7entynine** [comment]
Thanks for the quick response. I tried different 2FA versions but always get an error message with DKB. See issue #130 
Do you have your phone as the main access device registered in DKB?

**Comment by Jonsen94** [comment]
Getting the same error, any progress on this ?

**Comment by Jonsen94** [comment]
Did you enter the firefly url with a tailing / ? That was my mistake but now it works.

**Comment by loppermann-de** [comment]
For me, it works when I set “bank_2fa”: “NoPsd2TanMode”.
