### ISSUE TITLE
comdirect: Die Nachricht hat nicht die erwartete Nachrichtennummer.

### ISSUE THREAD

**Issue by msix81** [bnw/firefly-iii-fints-importer#135]
I tried to configure the FinTS Importer for a comdirect account, but received the error message `Die Nachricht hat nicht die erwartete Nachrichtennummer.` unfortunately.

Configuration (done via UI):
![image](https://github.com/user-attachments/assets/3b450b51-498d-4f3e-b1cf-dc4d729aa880)

The chosen Two-Factor Method doesn't really matter. My bank supports 901 and 902 (as confirmed by the error message when selecting another one), and the error is the same for both.

Any ideas?

Full stacktrace:
`Fatal error: Uncaught Fhp\Protocol\ServerException: FinTS errors: 9050 (global): Die Nachricht enthaelt Fehler. 9800 (global): Dialog abgebrochen 9120 (global): Die Nachricht hat nicht die erwartete Nachrichtennummer. in /vendor/nemiah/php-fints/lib/Fhp/Protocol/ServerException.php:170 Stack trace: #0 /vendor/nemiah/php-fints/lib/Fhp/FinTs.php(963): Fhp\Protocol\ServerException::detectAndThrowErrors(Object(Fhp\Protocol\Message), Object(Fhp\Protocol\Message)) #1 /vendor/nemiah/php-fints/lib/Fhp/FinTs.php(307): Fhp\FinTs->sendMessage(Object(Fhp\Protocol\Message)) #2 /vendor/nemiah/php-fints/lib/Fhp/FinTs.php(263): Fhp\FinTs->execute(Object(Fhp\Protocol\DialogInitialization)) #3 /app/Login.php(23): Fhp\FinTs->login() #4 /app/TanHandler.php(41): App\StepFunction\{closure}() #5 /app/TanHandler.php(31): App\TanHandler->create_or_continue_action() #6 /app/Login.php(21): App\TanHandler->__construct(Object(Closure), 'login-action', Object(Symfony\Component\HttpFoundation\Session\Session), Object(Twig\Environment), Object(Fhp\FinTs), Object(App\Step), Object(Symfony\Component\HttpFoundation\Request)) #7 /app/index.php(53): App\StepFunction\Login() #8 {main} thrown in /vendor/nemiah/php-fints/lib/Fhp/Protocol/ServerException.php on line 170`

**Comment by bnw** [comment]
Hi @msix81,
could [this](https://github.com/bnw/firefly-iii-fints-importer/issues/122#issuecomment-1972127982) here be the problem?
I suspect the error might occur because teh form is effectively submitted twice in this scenario.

**Comment by msix81** [comment]
You were right, thank you! I had to start a new browser session and not click on any "Proceed" button, but just wait for a couple of seconds. Now I am seeing another error ("cURL error 7: Failed to connect to localhost port 80 after 0 ms: Connection refused"), but I guess I have to follow up that one separately.
