### ISSUE TITLE
Ungültige Auftragsnachricht: Ungültige Signatur.

### ISSUE THREAD

**Issue by DestinyofYeet** [bnw/firefly-iii-fints-importer#150]
I am trying to automate the importing process with a systemd target which runs `curl -X GET "http://localhost:7070/?automate=true&config=targobank.json"` every day at 00:00.

However I am encountering following error.

(This is just one older example, it happens on every automated request)
```
Sep 18 00:00:00 nix-server systemd[1]: Starting import-firefly-data.service...
Sep 18 00:00:00 nix-server import-firefly-data-start[3897473]:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Sep 18 00:00:00 nix-server import-firefly-data-start[3897473]:                                  Dload  Upload   Total   Spent    Left  Speed
Sep 18 00:00:04 nix-server import-firefly-data-start[3897473]: [474B blob data]
Sep 18 00:00:04 nix-server import-firefly-data-start[3897473]: <br />
Sep 18 00:00:04 nix-server import-firefly-data-start[3897473]: <b>Fatal error</b>:  Uncaught Fhp\Protocol\ServerException: FinTS errors:
Sep 18 00:00:04 nix-server import-firefly-data-start[3897473]: 9050 (global): Die Nachricht enthält Fehler.
Sep 18 00:00:04 nix-server import-firefly-data-start[3897473]: 9800 (global): Dialog abgebrochen
Sep 18 00:00:04 nix-server import-firefly-data-start[3897473]: 9050 (global): ***Verarbeitung zur Zeit nicht möglich.***
Sep 18 00:00:04 nix-server import-firefly-data-start[3897473]: 9340 (global): Ungültige Auftragsnachricht: Ungültige Signatur. in /vendor/nemiah/php-fints/lib/Fhp/Protocol/ServerException.ph>
Sep 18 00:00:04 nix-server import-firefly-data-start[3897473]: Stack trace:
Sep 18 00:00:04 nix-server import-firefly-data-start[3897473]: #0 /vendor/nemiah/php-fints/lib/Fhp/FinTs.php(963): Fhp\Protocol\ServerException::detectAndThrowErrors(Object(Fhp\Protocol\Mess>
Sep 18 00:00:04 nix-server import-firefly-data-start[3897473]: #1 /vendor/nemiah/php-fints/lib/Fhp/FinTs.php(307): Fhp\FinTs-&gt;sendMessage(Object(Fhp\Protocol\Message))
Sep 18 00:00:04 nix-server import-firefly-data-start[3897473]: #2 /vendor/nemiah/php-fints/lib/Fhp/FinTs.php(832): Fhp\FinTs-&gt;execute(Object(Fhp\Protocol\DialogInitialization))
Sep 18 00:00:04 nix-server import-firefly-data-start[3897473]: #3 /vendor/nemiah/php-fints/lib/Fhp/FinTs.php(705): Fhp\FinTs-&gt;executeWeakDialogInitialization(NULL)
Sep 18 00:00:04 nix-server import-firefly-data-start[3897473]: #4 /vendor/nemiah/php-fints/lib/Fhp/FinTs.php(674): Fhp\FinTs-&gt;ensureSynchronized()
Sep 18 00:00:04 nix-server import-firefly-data-start[3897473]: #5 /vendor/nemiah/php-fints/lib/Fhp/FinTs.php(532): Fhp\FinTs-&gt;ensureTanModesAvailable()
Sep 18 00:00:04 nix-server import-firefly-data-start[3897473]: #6 /app/FinTsFactory.php(55): Fhp\FinTs-&gt;getTanModes()
Sep 18 00:00:04 nix-server import-firefly-data-start[3897473]: #7 /app/FinTsFactory.php(30): App\FinTsFactory::get_tan_mode(Object(Fhp\FinTs), Object(Symfony\Component\HttpFoundation\Session>
Sep 18 00:00:04 nix-server import-firefly-data-start[3897473]: #8 /app/CollectData.php(61): App\FinTsFactory::create_from_session(Object(Symfony\Component\HttpFoundation\Session\Session))
Sep 18 00:00:04 nix-server import-firefly-data-start[3897473]: #9 /app/index.php(51): App\StepFunction\CollectData()
Sep 18 00:00:04 nix-server import-firefly-data-start[3897473]: #10 {main}
Sep 18 00:00:04 nix-server import-firefly-data-start[3897473]:   thrown in <b>/vendor/nemiah/php-fints/lib/Fhp/Protocol/ServerException.php</b> on line <b>170</b><br />
Sep 18 00:00:04 nix-server import-firefly-data-start[3897542]: Successfully sent email!
Sep 18 00:00:04 nix-server systemd[1]: import-firefly-data.service: Deactivated successfully.
```

This is my configuration file

```json
{
  "bank_username": "xxx",
  "bank_password": "xxx",
  "bank_code": "xxx",
  "bank_url": "https://fints.targobank.de/travicretail_fints30pintanbroker/FinTs30PinTanHttpGate",
  "bank_2fa": "xxx",
  "bank_2fa_device": "",
  "firefly_url": "xxx",
  "firefly_access_token": "xxx",
  "skip_transaction_review": "false",
  "__description_regex_comment__": "To disable the regex search & replace of the transaction description, set both to an empty string.",
  "description_regex_match": "/^(Übertrag \\/ Überweisung|Lastschrift \\/ Belastung)(.*)(END-TO-END-REF.*|Karte.*|KFN.*)(Ref\\..*)$/mi",
  "description_regex_replace": "$2 [$1 | $3 | $4]",
  "auto_submit_form_via_js": false,
  "choose_account_automation":
  {
    "bank_account_iban": "xxx",
    "firefly_account_id": "1",
    "__from_to_comment__": "The following values will be passed directly into DateTime. Set them to null to choose them manually during import process.",
    "from": "now - 7 days",
    "to": "now"
  }
}
```

Running the configuration manually via the webui again does work and imports the data correctly.

**Comment by DestinyofYeet** [comment]
After changing the import time from 00:00 to 01:00 the error doesn't occur anymore. I *think* this is a solution.
