### ISSUE TITLE
FinTS exception for data import from comdirect visa credit card

### ISSUE THREAD

**Issue by le8266** [bnw/firefly-iii-fints-importer#151]
Hi,
I get the following exception when I want to import the data of the comdirect visa credit card:

```
Fatal error: Uncaught Fhp\Protocol\ServerException: FinTS errors: 
9050 (global): Die Nachricht enthaelt Fehler. 
9210 (wrt seg 3): Falsche Kontonummer oder falsches Unterkontomerkmal. [KTO=4263540112633051, TYP=Visa-Karte (Kreditkarte)] FinTS warnings: 
3905 (global): Es wurde keine Challenge erzeugt. Request segments: HKKAZ:3:5+4263540112633051:Visa-Karte (Kreditkarte):280:20041155+N+20240827+20240927' in /vendor/nemiah/php-fints/lib/Fhp/Protocol/ServerException.php:170
Stack trace: #0 /vendor/nemiah/php-fints/lib/Fhp/FinTs.php(962): Fhp\Protocol\ServerException::detectAndThrowErrors(Object(Fhp\Protocol\Message), Object(Fhp\Protocol\Message)) #1
/vendor/nemiah/php-fints/lib/Fhp/FinTs.php(306): Fhp\FinTs->sendMessage(Object(Fhp\Protocol\Message)) #2 /app/GetImportData.php(30): Fhp\FinTs->execute(Object(Fhp\Action\GetStatementOfAccount)) #3
/app/TanHandler.php(47): App\StepFunction\{closure}() #4
/app/TanHandler.php(31): App\TanHandler->create_or_continue_action() #5
/app/GetImportData.php(19): App\TanHandler->__construct(Object(Closure), 'soa', Object(Symfony\Component\HttpFoundation\Session\Session), Object(Twig\Environment), Object(Fhp\FinTs), Object(App\Step), Object(Symfony\Component\HttpFoundation\Request)) #6
/app/index.php(67): App\StepFunction\GetImportData() #7
{main} thrown in /vendor/nemiah/php-fints/lib/Fhp/Protocol/ServerException.php on line 170
```

Does anyone know the reason for this? Thanks for your help.

**Comment by bnw** [comment]
> Falsche Kontonummer oder falsches Unterkontomerkmal

I think you are using the wrong credentials for your bank.
Note that your FinTS credentials are not necessarily identical to the credentials you use on your banking website.
