### ISSUE TITLE
FinTS / DKB: Fatal Error: Zugriff auf BPD nicht möglich

### ISSUE THREAD

**Issue by meinnamehier** [bnw/firefly-iii-fints-importer#36]
Hi, i am using the docker container from benkl/firefly-iii-fints-importer
When trying to import data from DKB i get this error message:
`Fatal error: Uncaught Fhp\Protocol\ServerException: FinTS errors: 9050 (global): Die Nachricht enthält Fehler. 9800 (global): Dialog abgebrochen 9010 (global): Zugriff auf BPD nicht möglich. in /vendor/nemiah/php-fints/lib/Fhp/Protocol/ServerException.php:196 Stack trace: #0 /vendor/nemiah/php-fints/lib/Fhp/FinTs.php(925): Fhp\Protocol\ServerException::detectAndThrowErrors(Object(Fhp\Protocol\Message), Object(Fhp\Protocol\Message)) #1 /vendor/nemiah/php-fints/lib/Fhp/FinTs.php(576): Fhp\FinTs->sendMessage(Object(Fhp\Protocol\Message)) #2 /vendor/nemiah/php-fints/lib/Fhp/FinTs.php(602): Fhp\FinTs->ensureBpdAvailable() #3 /vendor/nemiah/php-fints/lib/Fhp/FinTs.php(464): Fhp\FinTs->ensureTanModesAvailable() #4 /app/FinTsFactory.php(55): Fhp\FinTs->getTanModes() #5 /app/FinTsFactory.php(30): App\FinTsFactory::get_tan_mode(Object(Fhp\FinTs), Object(Symfony\Component\HttpFoundation\Session\Session)) #6 /app/index.php(101): App\FinTsFactory::create_from_session(Object(Symfony\Component\HttpFoundation\Session\Session)) #7 {main in /vendor/nemiah/php-fints/lib/Fhp/Protocol/ServerException.php on line 196`

Do you need additional info?
Thanks a lot - i greatly appreciate your work!

**Comment by meinnamehier** [comment]
Ok, it is solved: I didn't understand that I needed to enter "12030000" in the "bank code" field.
It worked great once i did that.
