### ISSUE TITLE
Fatal error when importing data

### ISSUE THREAD

**Issue by nicolazilio** [bnw/firefly-iii-fints-importer#50]
After having successfully retrieved transactions, when I hit the 'Import transactions to FireflyIII' button I get the following error

`Fatal error: Uncaught GrumpyDictator\FFIIIApiSupport\Exceptions\ApiHttpException: Status code is 500: {"message":"Internal Firefly III Exception: Attempt to read property \"transaction_group_id\" on null","exception":"ErrorException"} in /mnt/sdcard/home/admin/www/budget/firefly-iii-fints-importer/vendor/firefly-iii/api-support-classes/src/Request/Request.php:311 Stack trace: #0 /mnt/sdcard/home/admin/www/budget/firefly-iii-fints-importer/vendor/firefly-iii/api-support-classes/src/Request/Request.php(235): GrumpyDictator\FFIIIApiSupport\Request\Request->authenticatedSubmission() #1 /mnt/sdcard/home/admin/www/budget/firefly-iii-fints-importer/vendor/firefly-iii/api-support-classes/src/Request/PostTransactionRequest.php(68): GrumpyDictator\FFIIIApiSupport\Request\Request->authenticatedPost() #2 /mnt/sdcard/home/admin/www/budget/firefly-iii-fints-importer/app/TransactionsToFireflySender.php(91): GrumpyDictator\FFIIIApiSupport\Request\PostTransactionRequest->post() #3 /mnt/sdcard/home/admin/www/budget/firefly-iii-fints-importer/app/index.php(275): App\TransactionsToFireflySender->send_transactions() #4 {main} thrown in /mnt/sdcard/home/admin/www/budget/firefly-iii-fints-importer/vendor/firefly-iii/api-support-classes/src/Request/Request.php on line 311`

Strangely it worked once, but because duplicate transactions don't seem to be detected anymore (this is another issue BTW), I ended up deleting all transactions for a period and tried to import them all back in in one go, and this is when the error showed up. 

Running the latest 'versions' of both firefly-iii and firefly-iii-fints-importer.

Any ideas?

**Comment by TyrionWarMage** [comment]
I think, this is this bug: https://github.com/firefly-iii/firefly-iii/issues/5145. Supposed to be fixed, but not no new release yet.
