### ISSUE TITLE
Undefined offset: 9xx

### ISSUE THREAD

**Issue by maltechx** [bnw/firefly-iii-fints-importer#8]
I'm getting the following error with every tan option listed. My bank (comdirect) should support SMS-TAN and Photo-TAN.
````
Notice: Undefined offset: 911 in /app/FinTsFactory.php on line 48

Fatal error: Uncaught Error: Call to a member function getId() on null in /app/FinTsFactory.php:49 Stack trace: #0 /app/FinTsFactory.php(29): App\FinTsFactory::get_tan_mode(Object(Fhp\FinTs), Object(Symfony\Component\HttpFoundation\Session\Session)) #1 /app/index.php(46): App\FinTsFactory::create_from_session(Object(Symfony\Component\HttpFoundation\Session\Session)) #2 {main} thrown in /app/FinTsFactory.php on line 49
````

**Comment by bnw** [comment]
Unfortunately I cannot reproduce this with my bank. For debugging it, I will need your help.  

Could you add `var_dump($finTs->getTanModes());` to `app/FinTsFactory.php:48` (where the warning happens) and post the results to show which available Tan Modes your bank reports?

**Comment by maltechx** [comment]
This is the response:
````
Notice: Undefined offset: 911 in /app/FinTsFactory.php on line 48
array(2) { [902]=> object(Fhp\Segment\TAN\VerfahrensparameterZweiSchrittVerfahrenV6)#263 (21) { ["sicherheitsfunktion"]=> int(902) ["tanProzess"]=> int(2) ["technischeIdentifikationTanVerfahren"]=> string(7) "MS1.0.0" ["zkaTanVerfahren"]=> NULL ["versionZkaTanVerfahren"]=> NULL ["nameDesZweiSchrittVerfahrens"]=> string(18) "photoTAN-Verfahren" ["maximaleLaengeDesTanEingabewertes"]=> int(6) ["erlaubtesFormat"]=> int(1) ["textZurBelegungDesRueckgabewertes"]=> string(23) "Freigabe durch photoTAN" ["maximaleLaengeDesRueckgabewertes"]=> int(1) ["mehrfachTanErlaubt"]=> bool(false) ["tanZeitUndDialogbezug"]=> int(4) ["auftragsstornoErlaubt"]=> bool(false) ["smsAbbuchungskontoErforderlich"]=> int(0) ["auftraggeberkontoErforderlich"]=> int(0) ["challengeKlasseErforderlich"]=> bool(false) ["challengeStrukturiert"]=> bool(false) ["initialisierungsmodus"]=> string(2) "00" ["bezeichnungDesTanMediumsErforderlich"]=> int(0) ["antwortHhdUcErforderlich"]=> bool(false) ["anzahlUnterstuetzterAktiverTanMedien"]=> NULL } [901]=> object(Fhp\Segment\TAN\VerfahrensparameterZweiSchrittVerfahrenV6)#259 (21) { ["sicherheitsfunktion"]=> int(901) ["tanProzess"]=> int(2) ["technischeIdentifikationTanVerfahren"]=> string(14) "TechnicalId901" ["zkaTanVerfahren"]=> NULL ["versionZkaTanVerfahren"]=> NULL ["nameDesZweiSchrittVerfahrens"]=> string(19) "mobileTAN-Verfahren" ["maximaleLaengeDesTanEingabewertes"]=> int(6) ["erlaubtesFormat"]=> int(1) ["textZurBelegungDesRueckgabewertes"]=> string(24) "Freigabe durch mobileTAN" ["maximaleLaengeDesRueckgabewertes"]=> int(1) ["mehrfachTanErlaubt"]=> bool(false) ["tanZeitUndDialogbezug"]=> int(4) ["auftragsstornoErlaubt"]=> bool(false) ["smsAbbuchungskontoErforderlich"]=> int(0) ["auftraggeberkontoErforderlich"]=> int(0) ["challengeKlasseErforderlich"]=> bool(false) ["challengeStrukturiert"]=> bool(false) ["initialisierungsmodus"]=> string(2) "00" ["bezeichnungDesTanMediumsErforderlich"]=> int(0) ["antwortHhdUcErforderlich"]=> bool(false) ["anzahlUnterstuetzterAktiverTanMedien"]=> NULL } }
Fatal error: Uncaught Error: Call to a member function getId() on null in /app/FinTsFactory.php:50 Stack trace: #0 /app/FinTsFactory.php(29): App\FinTsFactory::get_tan_mode(Object(Fhp\FinTs), Object(Symfony\Component\HttpFoundation\Session\Session)) #1 /app/index.php(46): App\FinTsFactory::create_from_session(Object(Symfony\Component\HttpFoundation\Session\Session)) #2 {main} thrown in /app/FinTsFactory.php on line 50
````

**Comment by bnw** [comment]
I have added the two options advertised by your bank: "photoTAN" and "mobileTAN".
Could you try if these work for you?

**Comment by maltechx** [comment]
Works as expected.
Thanks for your fast response and fix.

**Comment by bnw** [comment]
:)
