### ISSUE TITLE
Can't get comdirect running

### ISSUE THREAD

**Issue by totti4ever** [bnw/firefly-iii-fints-importer#9]
```
Fatal error: Uncaught Fhp\Protocol\ServerException: FinTS errors: 9050 (global): Die Nachricht enthaelt Fehler. 9800 (global): Dialog abgebrochen 9010 (global): Benutzer unbekannt. 9340 (global): Ungueltige Auftragsnachricht: Ungueltige Signatur. in /vendor/nemiah/php-fints/lib/Fhp/Protocol/ServerException.php:196 Stack trace: #0 /vendor/nemiah/php-fints/lib/Fhp/FinTs.php(925): Fhp\Protocol\ServerException::detectAndThrowErrors(Object(Fhp\Protocol\Message), Object(Fhp\Protocol\Message)) #1 /vendor/nemiah/php-fints/lib/Fhp/FinTs.php(353): Fhp\FinTs->sendMessage(Object(Fhp\Protocol\Message)) #2 /vendor/nemiah/php-fints/lib/Fhp/FinTs.php(312): Fhp\FinTs->sendRequestForAction(Object(Fhp\Protocol\DialogInitialization), Object(Fhp\Protocol\Message)) #3 /vendor/nemiah/php-fints/lib/Fhp/FinTs.php(789): Fhp\FinTs->execute(Object(Fhp\Protocol\DialogInitialization)) #4 /vendor/nemiah/php-fints/lib/Fhp/FinTs.php(632): Fhp\FinTs->executeWeakDialogInitialization(NULL) #5 /vendor/nemiah/php-fints/lib/Fhp/FinTs.php(603): Fhp\FinTs->ensur in /vendor/nemiah/php-fints/lib/Fhp/Protocol/ServerException.php on line 196

```

**Comment by bnw** [comment]
In the error Message it says "Benutzer unbekannt.", so I'm assuming that you provide an incorrect username for your bank.  
For my bank (DKB) it's the same username as for the Online-Banking interface.

**Comment by totti4ever** [comment]
Stupid me, thank you!

**Comment by bnw** [comment]
:)
