### ISSUE TITLE
[Bug?] error message

### ISSUE THREAD

**Issue by mtettke123** [bnw/firefly-iii-fints-importer#99]
when connecting to my account (Berliner Volksbank), the following message occurs:

`Fatal error: Uncaught InvalidArgumentException: "Bearer eyJ0eXAi[...]7cU82O0HxaNHokU " is not valid header value in /vendor/guzzlehttp/psr7/src/MessageTrait.php:263 Stack trace: #0 /vendor/guzzlehttp/psr7/src/MessageTrait.php(209): GuzzleHttp\Psr7\Request->assertValue('Bearer eyJ0eXAi...') #1 [internal function]: GuzzleHttp\Psr7\Request->GuzzleHttp\Psr7\{closure}('Bearer eyJ0eXAi...') #2 /vendor/guzzlehttp/psr7/src/MessageTrait.php(212): array_map(Object(Closure), Array) #3 /vendor/guzzlehttp/psr7/src/MessageTrait.php(174): GuzzleHttp\Psr7\Request->trimAndValidateHeaderValues(Array) #4 /vendor/guzzlehttp/psr7/src/MessageTrait.php(154): GuzzleHttp\Psr7\Request->normalizeHeaderValue('Bearer eyJ0eXAi...') #5 /vendor/guzzlehttp/psr7/src/Request.php(49): GuzzleHttp\Psr7\Request->setHeaders(Array) #6 /vendor/guzzlehttp/guzzle/src/Client.php(164): GuzzleHttp\Psr7\Request->__construct('GET', Object(GuzzleHttp\Psr7\Uri), Array, NULL, '1.1') #7 /vendor/guzzlehttp/guzzle/src/Client.php(187): GuzzleHttp\Client->requestAsync('GET', Object(GuzzleHttp\Psr7\Uri), Array) #8 /vendor/firefly-iii/api-support-classes/src/Request/Request.php(192): GuzzleHttp\Client->request('GET', 'http://app:8080...', Array) #9 /vendor/firefly-iii/api-support-classes/src/Request/GetAccountsRequest.php(80): GrumpyDictator\FFIIIApiSupport\Request\Request->authenticatedGet() #10 /app/ChooseAccount.php(38): GrumpyDictator\FFIIIApiSupport\Request\GetAccountsRequest->get() #11 /app/index.php(57): App\StepFunction\ChooseAccount() #12 {main} thrown in /vendor/guzzlehttp/psr7/src/MessageTrait.php on line 263`

Can anyone give me a hint?

**Comment by mtettke123** [comment]
Sorry, solved, wrong internal hostname.

**Comment by mtettke123** [comment]
see above
